### ISSUE TITLE
About relative Paths 

### ISSUE THREAD

**Issue by crustamet** [bpedroza/asset-compiler#1]
Can you change the relative paths and let the user put full path to the files

i had to do crazy shit like this 

	$cssAssets = [
		'bootstrap.min.css',
		'../../../core/css/adminpanel.css',
		'../../../icons/fontawesome5/css/all.min.css'
	];

same as for JsAssets

at some point i was guessing the paths. 

It does not work with full path to files because it will be prefixed with a CSS folder.
so i had to trick the script to exit the path and go to the right path relatively

This just sucks ass bro.
I hope you will get this fixed, it is crazy for putting all the time paths like this ../../../

And you probably can get rid of the 
cssPath, jsPath, completely...

I got multiple folders with css files and js files so i always have to guess the path to it.

Or maybe there is a way for this that i don't know ?
Can you be so kind and help me with this ?

**Comment by bpedroza** [comment]
Using a full path might be workable for the files that will be compiled or minimized, but it wouldn't work for single files, or when debug is set to true.

To be honest, this is kind of hard to even make a suggestion on without knowing if these paths are public or available for linking a script.

At a glance I could suggest: 
Make your css path whatever the lowest path is (whatever `../../../` is) then your assets array will be:
```php
$cssAssets = [
	'my/super/duper/deep/css/folder/bootstrap.min.css',
	'core/css/adminpanel.css',
	'icons/fontawesome5/css/all.min.css'
];
```
You can make the css or js paths just an empty string. It's all configurable, so it's up to you.

I think what you want is both css and js paths empty, with the assets path whatever `../../../` is. Your compiled css and js files will then both land in the `/compiled` folder, and it should work fine. I haven't tested this type of configuration, so you might need to play around with it a bit.

I'm not going to change the behavior. 
If this is a deal breaker for you and you can't get it working as you would like with different configuration options, I suggest: 

1. consider a different tool
2. restructure your assets in a way this tool is meant to be used (css files together, js files together)
3. Keep using relative paths. It's really not that big of a deal.

**Comment by bpedroza** [comment]
@crustamet Can you please let me know if you got it working with the suggested configuration changes or not?
If you did I think it might be helpful to others to update the documentation to give example for use cases like yours.

**Comment by crustamet** [comment]
i didn't talk about single files, i am talking about when compiling with multiple files from multiple paths.

As i told you, i have it working anyway, but i always have to guess the relative paths.
I tried to modify your app but i failed, i don't know how it works really xD

It would be awsome if you can put full paths, i am using a framework, sometimes my controllers are in another directory, i have to change all scripts with another ../ prefix, sucks though

**Comment by crustamet** [comment]
Maybe i am using it wrong lol..

**Comment by bpedroza** [comment]
@crustamet Please see my recommendation:

>I think what you want is both css and js paths empty, with the assets path whatever ../../../ is. Your compiled css and js files will then both land in the /compiled folder, and it should work fine. I haven't tested this type of configuration, so you might need to play around with it a bit.

I think that type of configuration would work more like you expect.
